export const usePackageStore = defineStore("package", () => {
  const packages = ref([
    {
      id: 1,
      name: "Economy",
      price: "100000.00",
      discount: null,
      features: [
        "50 tamu undangan + grup",
        "Akses tema standar",
        "4 foto galeri (max)",
        "Informasi acara",
        "Background musik (list)",
        "Timer countdown",
        "Maps lokasi",
        "Tambah ke kalender",
        "Story",
        "RSVP",
        "Ucapan tamu",
        "3 bulan masa aktif",
      ],
    },
    {
      id: 2,
      name: "Premium",
      price: "200000.00",
      discount: 25,
      features: [
        "250 tamu undangan + grup",
        "Akses tema premium",
        "10 foto galeri (max)",
        "1 video",
        "Informasi acara",
        "Background musik custom",
        "Timer countdown",
        "Maps lokasi",
        "Tambah ke kalender",
        "Story",
        "RSVP",
        "Ucapan tamu",
        "Kirim hadiah",
        "6 bulan masa aktif",
      ],
    },
    {
      id: 3,
      name: "Business",
      price: "300000.00",
      discount: 15,
      features: [
        "1000 tamu undangan + grup",
        "Akses tema premium",
        "20 foto galeri (max)",
        "5 video (max)",
        "Informasi acara",
        "Background musik custom",
        "Timer countdown",
        "Maps lokasi",
        "Tambah ke kalender",
        "Story",
        "RSVP",
        "Ucapan tamu",
        "Kirim hadiah",
        "6 bulan masa aktif",
      ],
    },
  ]);

  return {
    packages,
  };
});
