export const usePackageStore = defineStore("package", () => {
  const packages = ref([
    {
      id: 1,
      name: "Free",
      price: "0.00",
      discount: null,
      features: [
        "10 tamu undangan",
        "Akses tema standar",
        "2 foto galeri (max)",
        "Import kontak",
        "Informasi acara",
        "Timer countdown",
        "Maps lokasi",
        "Tambah ke kalender",
        "Story",
        "RSVP",
        "Ucapan tamu",
        "7 hari masa aktif",
      ],
    },
    {
      id: 2,
      name: "Economy",
      price: "100000.00",
      discount: 10,
      features: [
        "250 tamu undangan + grup",
        "Akses tema standar",
        "4 foto galeri (max)",
        "Background musik (list)",
        "Import kontak",
        "Informasi acara",
        "Timer countdown",
        "Maps lokasi",
        "Tambah ke kalender",
        "Story",
        "RSVP",
        "Ucapan tamu",
        "3 bulan masa aktif",
      ],
    },
    {
      id: 3,
      name: "Premium",
      price: "200000.00",
      discount: 25,
      features: [
        "1000 tamu undangan + grup",
        "Akses tema premium",
        "10 foto galeri (max)",
        "1 video",
        "Background musik custom",
        "Kirim hadiah",
        "Import kontak",
        "Informasi acara",
        "Timer countdown",
        "Maps lokasi",
        "Tambah ke kalender",
        "Story",
        "RSVP",
        "Ucapan tamu",
        "6 bulan masa aktif",
      ],
    },
    {
      id: 4,
      name: "Business",
      price: "300000.00",
      discount: 15,
      features: [
        "Unlimited tamu undangan + grup",
        "Akses tema premium",
        "20 foto galeri (max)",
        "5 video (max)",
        "Background musik custom",
        "Kirim hadiah",
        "Import kontak",
        "Informasi acara",
        "Timer countdown",
        "Maps lokasi",
        "Tambah ke kalender",
        "Story",
        "RSVP",
        "Ucapan tamu",
        "1 tahun masa aktif",
      ],
    },
  ]);

  return {
    packages,
  };
});
